import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  // ...existing code from styles object in index.tsx...
  titleContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    marginBottom: 8,
  },
  labTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#1976d2",
    textAlign: "center",
    marginBottom: 0,
    letterSpacing: 0.2,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#023c69",
    textAlign: "center",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 18,
    paddingBottom: 2,
    backgroundColor: "#f5f5f5",
    minHeight: 48,
  },
  settingsButton: {
    padding: 6,
    marginLeft: 8,
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    alignSelf: "flex-end",
  },
  connBar: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    marginBottom: 6,
    flexDirection: "row",
    backgroundColor: "#f5f5f5",
  },
  connectButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1976d2",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
  },
  connectButtonText: {
    color: "#fff",
    fontWeight: "bold",
    marginLeft: 8,
    fontSize: 15,
  },
  landscapeContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingBottom: 18,
    gap: 12,
  },
  portraitContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    paddingHorizontal: 18,
    paddingBottom: 18,
    gap: 12,
  },
  leftPanel: {
    flex: 1.2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  rightPanel: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  portraitPanel: {
    flex: 1,
    justifyContent: "flex-start",
    marginVertical: 0,
  },
  portraitSpeedPanel: {
    marginTop: 0,
  },
  speedPortraitWrapper: {
    marginTop: 40,
    marginBottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  controllerContainer: {
    alignItems: "center",
    marginBottom: 10,
    marginTop: 0,
  },
  dpadRow: {
    flexDirection: "row",
    justifyContent: "center",
  },
  dpadButton: {
    width: 80,
    height: 80,
    margin: 5,
    borderRadius: 40,
    backgroundColor: "#e0e0e0",
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
  },
  dpadText: {
    fontSize: 44,
    fontWeight: "bold",
  },
  speedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 5,
  },
  speedButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#b0c4de",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 18,
  },
  speedText: {
    fontSize: 44,
    fontWeight: "bold",
  },
  speedValue: {
    fontSize: 44,
    fontWeight: "bold",
    minWidth: 60,
    textAlign: "center",
  },
  speedLabel: {
    fontSize: 16,
    color: "#555",
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    width: "85%",
    maxWidth: 400,
    alignItems: "center",
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  connectedInfoText: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontSize: 14,
    color: "#333",
  },
  disconnectButton: {
    marginTop: 5,
    backgroundColor: "#e57373",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
  },
  disconnectButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 13,
  },
  deviceItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#fff",
    marginBottom: 2,
    borderRadius: 5,
  },
  connectedDevice: {
    backgroundColor: "#d0ffd0",
  },
  rescanButton: {
    marginTop: 10,
    backgroundColor: "#b0c4de",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 90,
    minHeight: 40,
  },
  rescanButtonText: {
    color: "#222",
    fontWeight: "bold",
    fontSize: 14,
  },
  closeButton: {
    marginTop: 10,
    backgroundColor: "#888",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 90,
    minHeight: 40,
    marginLeft: 0,
  },
  closeButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
  settingsTab: {
    flex: 1,
    paddingVertical: 8,
    borderBottomWidth: 2,
    borderColor: "transparent",
    alignItems: "center",
  },
  settingsTabActive: {
    borderColor: "#1976d2",
  },
  settingsTabText: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#1976d2",
  },
  saveButton: {
    backgroundColor: "#1976d2",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 90,
    minHeight: 40,
    marginTop: 10,
    marginLeft: 0,
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
  commandInput: {
    borderWidth: 1,
    borderColor: "#bbb",
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 2,
    minWidth: 60,
    fontSize: 15,
    backgroundColor: "#f9f9f9",
    marginLeft: 8,
  },
});

export default styles;
